version: '2.2'
services:
  essingle:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - node.name=essingle
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - data01:/usr/share/elasticsearch/data
    shm_size: 1G
    restart: always
#    restart: on-failure
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      ELASTICSEARCH_URL: http://essingle:9200
      ELASTICSEARCH_HOSTS: http://essingle:9200
    depends_on:
      -  essingle
    links:
      - essingle
    restart: always
#    restart: on-failure
    ports:
      - 5601:5601
  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.0
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m -Dlog4j2.formatMsgNoLookups=true"
    depends_on:
      -  essingle
    links:
      - essingle
    restart: always
#    restart: on-failure
    ports:
      - "514:1514/tcp" # syslog
      - "514:1514/udp" # syslog
    #   - "5000:5000/tcp"
    #   - "5000:5000/udp"
    #   - "9600:9600"


# Reference: https://github.com/deviantony/docker-elk
